### PR TITLE
added readme header color support

### PR DESCRIPTION
**Pull request by Dumbo-programmer**

### CODE REVIEW

**Comment by nexxeln** [comment]
would the colors show up on github tho? im not sure

**Comment by Dhravya** [comment]
@Dumbo-programmer Have you tested it out?

**Comment by Dumbo-programmer** [comment]
yea,take a look at the code it generates html with color in markdown and As far as I know it is rendered

**Comment by nexxeln** [comment]
it is rendered yeah, but not on github's flavour of markdown. they don't allow colours afaik.

**Comment by Dumbo-programmer** [comment]
guys! I was able to do this via images and api

**Comment by Dumbo-programmer** [comment]
now all is left is to update it

**Pull request closed without merging**
